### ISSUE TITLE
[Extensions sites] Certificate expiring soon

### ISSUE THREAD

**Issue by pygillier** [bolt/site-v20#11]
(more a reminder than anything else, issues are disabled on bolt-extensions)

Certificate used on extensions.bolt.cm is due to expire on 28/08/2015.

**Comment by GawainLynch** [comment]
Fixed! Thank you kindly for the reminder!

```
Issued On	Wednesday, 12 August 2015 at 01:00:00
Expires On	Saturday, 27 August 2016 at 00:59:59
```
