### ISSUE TITLE
CSS filter doesn't work in showcase page, under FF

### ISSUE THREAD

**Issue by rixbeck** [bolt/site-v20#12]
(21.36.46) realitygaps: hmm bolt.cm/showcase only shows images when hovered on in firefox on linux here
(21.37.01) realitygaps: was showing off bolt and came across it
(21.37.20) realitygaps: so its a page of blank image placeholders

**Comment by sbonardt** [comment]
Looks like it's the applied filter css effect in firefox that's not working.

.hover-dark {
    -moz-user-select: none;
    border: 1px solid #cfcfcf;
    cursor: pointer;
    filter: url("grayscale.svg");
    transition-duration: 1s;
}
