### ISSUE TITLE
Wrong link "upgrading" on features page.

### ISSUE THREAD

**Issue by gander** [bolt/site-v20#7]
On page https://bolt.cm/features in section ***For Frontend developers*** in block ***Easy to install and setup*** in text ***Bolt is easy to install and upgrade*** is wrong url in second link. I think it should be ***update*** and links to ***http://docs.bolt.cm/updating***.

**Comment by anketwokings** [comment]
Sorry it took so long to fix a typo. ;)
Fixed!
